export const cardsData = [
  {
    id: 1,
    title: "task 1",
    datetime: "24/1/2022 16:40 hs.",
    creator: "Axel Tur Springer",
    descripcion: "Generic descripcion",
    type: "new",
    priority: "high",
  },
  {
    id: 2,
    title: "task 2",
    datetime: "24/1/2022 16:40 hs.",
    creator: "Axel Tur Springer",
    descripcion: "Generic descripcion",
    type: "new",
    priority: "high",
  },
  {
    id: 3,
    title: "task 3",
    datetime: "24/1/2022 16:40 hs.",
    creator: "Axel Tur Springer",
    descripcion: "Generic descripcion",
    type: "new",
    priority: "high",
  },
  {
    id: 4,
    title: "task 4",
    datetime: "24/1/2022 16:40 hs.",
    creator: "Axel Tur Springer",
    descripcion: "Generic descripcion",
    type: "new",
    priority: "high",
  },
  {
    id: 5,
    title: "task 5",
    datetime: "24/1/2022 16:40 hs.",
    creator: "Axel Tur Springer",
    descripcion: "Generic descripcion",
    type: "new",
    priority: "high",
  },
  {
    id: 6,
    title: "task 6",
    datetime: "24/1/2022 16:40 hs.",
    creator: "Axel Tur Springer",
    descripcion: "Generic descripcion",
    type: "new",
    priority: "high",
  },
];
